#log:
#  level: DEBUG
# Раскомментировать только в случае необходимости выведения в консоль всей информации о работе traefik

providers:
  docker: true

# Название точки входа, к которой будут подключатся другие контейнеры.
# может быть любым. Главное, чтобы совпадал с названием в других местах.
entrypoints:
  web:
    address: :80
  websecure:
    address: :443

certificatesresolvers:
  myresolver:
    # Название может быть любым. К этому блоку будут обращатся контейнеры для получения сертификатов
    acme:
      # Здесь будут находится настройки для получения сертификатов.
      storage: /etc/traefik/acme.json
      email: YOUR_EMAIL_ADDRESS@gmail.com
      httpChallenge:
        # used during the challenge
        entryPoint: web
      # Включаем сохранение информации о полученых сертификатах в папку "traefik",
      # чтобы не генерировать их каждый раз при запуске контейнера.
      # Если сертификат ранее был создан и является актуальным,
      # то traefik возьмет его из файла "acme.json"

api:
  dashboard: true
